
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABSTRACT AMPERSAND AND_OP ARRAY ARROW AS ASSIGN BACKSLASH BOOL BREAK CASE CATCH CLASS COLON COMMA CONCAT_ASSIGN CONST CONTINUE DECREMENT DEFAULT DEFINE DIVIDE DIVIDE_ASSIGN DOT ECHO ELSE ELSEIF EQ EXTENDS FALSE FINAL FINALLY FLOAT FOR FOREACH FUNCTION GE GT ID IDENTICAL IF IMPLEMENTS INCLUDE INCLUDE_ONCE INCREMENT INSTANCEOF INTEGER INTERFACE LBRACE LBRACKET LE LPAREN LT MINUS MINUS_ASSIGN MOD NAMESPACE NE NEW NOT_OP NULL OBJECT_OP OR_OP PHP_CLOSE PHP_OPEN PLUS PLUS_ASSIGN POW PRIVATE PROTECTED PUBLIC RBRACE RBRACKET REQUIRE REQUIRE_ONCE RETURN RPAREN SEMICOLON STATIC STRING SUPERGLOBALS SWITCH THIS_VAR THROW TIMES TIMES_ASSIGN TRAIT TRUE TRY USE VARIABLE WHILE XOR_OPprograma : asigReferencia\n               | expressBolasigReferencia : VARIABLE ASSIGN AMPERSAND VARIABLE SEMICOLONexpressBol : operacionComparacion \n                    | operacionLogicooperacionComparacion : valor operadorCom valor operacionLogico : termLogico operadorLogico termLogicotermLogico : LPAREN operacionComparacion RPAREN \n                | BOOL valor : INTEGER\n            | FLOAT\n            | VARIABLEoperadorCom : EQ\n                 | NE\n                 | LT\n                 | GE\n                 | LE\n                 | GToperadorLogico : AND_OP\n                       | OR_OP\n                       | NOT_OP\n                       | XOR_OP'
    
_lr_action_items = {'VARIABLE':([0,11,14,15,16,17,18,19,20,28,],[4,27,27,-13,-14,-15,-16,-17,-18,32,]),'INTEGER':([0,11,14,15,16,17,18,19,20,],[9,9,9,-13,-14,-15,-16,-17,-18,]),'FLOAT':([0,11,14,15,16,17,18,19,20,],[10,10,10,-13,-14,-15,-16,-17,-18,]),'LPAREN':([0,21,22,23,24,25,],[11,11,-19,-20,-21,-22,]),'BOOL':([0,21,22,23,24,25,],[12,12,-19,-20,-21,-22,]),'$end':([1,2,3,5,6,9,10,12,27,29,30,31,33,],[0,-1,-2,-4,-5,-10,-11,-9,-12,-6,-7,-8,-3,]),'ASSIGN':([4,],[13,]),'EQ':([4,7,9,10,27,],[-12,15,-10,-11,-12,]),'NE':([4,7,9,10,27,],[-12,16,-10,-11,-12,]),'LT':([4,7,9,10,27,],[-12,17,-10,-11,-12,]),'GE':([4,7,9,10,27,],[-12,18,-10,-11,-12,]),'LE':([4,7,9,10,27,],[-12,19,-10,-11,-12,]),'GT':([4,7,9,10,27,],[-12,20,-10,-11,-12,]),'AND_OP':([8,12,31,],[22,-9,-8,]),'OR_OP':([8,12,31,],[23,-9,-8,]),'NOT_OP':([8,12,31,],[24,-9,-8,]),'XOR_OP':([8,12,31,],[25,-9,-8,]),'RPAREN':([9,10,26,27,29,],[-10,-11,31,-12,-6,]),'AMPERSAND':([13,],[28,]),'SEMICOLON':([32,],[33,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'asigReferencia':([0,],[2,]),'expressBol':([0,],[3,]),'operacionComparacion':([0,11,],[5,26,]),'operacionLogico':([0,],[6,]),'valor':([0,11,14,],[7,7,29,]),'termLogico':([0,21,],[8,30,]),'operadorCom':([7,],[14,]),'operadorLogico':([8,],[21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> asigReferencia','programa',1,'p_programa','sintactico.py',12),
  ('programa -> expressBol','programa',1,'p_programa','sintactico.py',13),
  ('asigReferencia -> VARIABLE ASSIGN AMPERSAND VARIABLE SEMICOLON','asigReferencia',5,'p_asigReferencia','sintactico.py',16),
  ('expressBol -> operacionComparacion','expressBol',1,'p_expressBol','sintactico.py',20),
  ('expressBol -> operacionLogico','expressBol',1,'p_expressBol','sintactico.py',21),
  ('operacionComparacion -> valor operadorCom valor','operacionComparacion',3,'p_operacionComparacion','sintactico.py',24),
  ('operacionLogico -> termLogico operadorLogico termLogico','operacionLogico',3,'p_operacionLogico','sintactico.py',27),
  ('termLogico -> LPAREN operacionComparacion RPAREN','termLogico',3,'p_termLogico','sintactico.py',30),
  ('termLogico -> BOOL','termLogico',1,'p_termLogico','sintactico.py',31),
  ('valor -> INTEGER','valor',1,'p_valor','sintactico.py',34),
  ('valor -> FLOAT','valor',1,'p_valor','sintactico.py',35),
  ('valor -> VARIABLE','valor',1,'p_valor','sintactico.py',36),
  ('operadorCom -> EQ','operadorCom',1,'p_operadorCom','sintactico.py',39),
  ('operadorCom -> NE','operadorCom',1,'p_operadorCom','sintactico.py',40),
  ('operadorCom -> LT','operadorCom',1,'p_operadorCom','sintactico.py',41),
  ('operadorCom -> GE','operadorCom',1,'p_operadorCom','sintactico.py',42),
  ('operadorCom -> LE','operadorCom',1,'p_operadorCom','sintactico.py',43),
  ('operadorCom -> GT','operadorCom',1,'p_operadorCom','sintactico.py',44),
  ('operadorLogico -> AND_OP','operadorLogico',1,'p_operadorLogico','sintactico.py',47),
  ('operadorLogico -> OR_OP','operadorLogico',1,'p_operadorLogico','sintactico.py',48),
  ('operadorLogico -> NOT_OP','operadorLogico',1,'p_operadorLogico','sintactico.py',49),
  ('operadorLogico -> XOR_OP','operadorLogico',1,'p_operadorLogico','sintactico.py',50),
]
